# Generated by Django 3.2.4 on 2022-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clsUser',
            fields=[
                ('pk_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vhr_user_name', models.CharField(blank=True, max_length=30)),
                ('vhr_actual_name', models.CharField(blank=True, max_length=30)),
                ('vhr_password', models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
