# Generated by Django 3.2.4 on 2022-07-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsItem',
            fields=[
                ('pk_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vhr_item_name', models.CharField(blank=True, max_length=30)),
                ('txt_item_description', models.TextField()),
                ('dbl_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
