# Generated by Django 3.2.4 on 2022-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clsitem',
            name='vhr_item_category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
